disabled_rules: # rule identifiers to exclude from running
  - line_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Signing
  - Pods
  - Podfile
  - Podfile.lock

identifier_name:
  excluded:
    - id
